const chatBot = require('../routes/chatbot')
// const payment = require('../routes/payment')
const bus = require('../routes/buses')
const booking = require('../routes/booking')
const seat = require('../routes/seat')
const route = require('../routes/route')
const user =  require('../routes/users')
const auth = require('../routes/auth')
const express = require('express')

module.exports = function(app){
    app.use(express.json()) 
    app.use(express.urlencoded())
    app.use('/api/v1/user',user)
    app.use('/api/v1/login',auth)
    app.use('/api/v1/route',route)
    app.use('/api/v1/seat', seat)
    app.use('/api/v1/booking', booking)
    app.use('/api/v1/bus',bus)
    // app.use('/api/v1/payment',payment)
    app.use('/api/chatbot',chatBot)
}